### ISSUE TITLE
Problem showing display at full screen

### ISSUE THREAD

**Issue by admilne** [josiaho/cordova-plugin-app-wkwebview-external-screen#1]
Fab plugin - this has really helped, so thanks!

I seem to be having an issue with the external screen having a black border around the display. It seems the resolution is being detected and the aspect ratio appears to be correct but perhaps it's being scaled down slightly. Is there a way to force this to display full screen?

**Comment by josiaho** [comment]
Hi! It sounds like your display device may require overscan correction. Try adding this line in `WKWebViewExternalScreen.m` after line 15:

`externalScreen.overscanCompensation = 3;`

In context:

`UIScreen* externalScreen = [[UIScreen screens] objectAtIndex: 1];`
`externalScreen.overscanCompensation = 3;`
`CGRect screenBounds = externalScreen.bounds;`

**Comment by admilne** [comment]
Ah great, I don't fully understand what is happening here but that has fixed the issue. Thanks!
